### ISSUE TITLE
maybe you also use this more detailed set of data about Italy 

### ISSUE THREAD

**Issue by dogi** [ploner/coronavirus-py#1]
https://github.com/pcm-dpc/COVID-19/blob/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv

**Comment by dogi** [comment]
![image](https://user-images.githubusercontent.com/13684059/77937627-99cec000-7282-11ea-8ab5-fb8344fe9f19.png)

**Comment by ploner** [comment]
Good point. On the other hand, it's rather a showcase app, so I really wanted to get all the data from the same (quite trusted) source. If you like you can fork the app and adapt the Italian data ;)

**Comment by ploner** [comment]
@dogi - ic, there are also detailed data by Italian region and less-detailed data on provinces. This would really make sense... https://github.com/pcm-dpc/COVID-19/tree/master/dati-regioni. 

Thx for the link.
