### ISSUE TITLE
Great work!! - Minor tweaks

### ISSUE THREAD

**Issue by paseman** [ploner/coronavirus-py#3]
Just installed conda and python3.  Had to make these (minor) changes to get you app to work.
                    #value=['Confirmed', 'Deaths']
                    values=['Confirmed', 'Deaths']

    #[Input('country', 'value'), Input('state', 'value'), Input('metrics', 'value'), Input('interval-component', 'n_intervals')]
    [Input('country', 'value'), Input('state', 'value'), Input('metrics', 'values'), Input('interval-component', 'n_intervals')]

**Comment by ploner** [comment]
Hi @paseman , good if it works! But strange, at least I had not to change the return value of dcc.Checklist to `values` in order to make it work. Bests, M
